### PR TITLE
🗜 Optimized CSS and JS | Minimal changes 📦

### PR DESCRIPTION
**Pull request by sahillangoo**
=> Optimized and prefixed CSS & JS;
=> Added loder to index.html
=> Few minimal changes.
=> SEO

### CODE REVIEW

**Comment by haideralipunjabi** [comment]
I reverted the PR after deploying after previewing it. The page-level loader isn't good as it will conflict with our PWA.

**Comment by haideralipunjabi** [comment]
Also, you don't need to minify or change the css as the website uses [purgecss](https://purgecss.com/) before deploying

**Comment by SahilLangoo** [comment]
Oh! forgot about that!
What About SEO

**Comment by sahillangoo** [comment]
Oh Forgot About That!

**Pull request merged**
